require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

module Product
  RSpec.describe "/products", type: :request do
        include Engine.routes.url_helpers
  
    # This should return the minimal set of attributes required to create a valid
    # Product. As you add validations to Product, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    describe "GET /index" do
      xit "renders a successful response" do
        Product::Product.create! valid_attributes
        get products_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      xit "renders a successful response" do
        product = Product::Product.create! valid_attributes
        get product_url(product)
        expect(response).to be_successful
      end
    end

    describe "GET /new" do
      xit "renders a successful response" do
        get new_product_url
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      xit "renders a successful response" do
        product = Product.create! valid_attributes
        get edit_product_url(product)
        expect(response).to be_successful
      end
    end

    describe "POST /create" do
      context "with valid parameters" do
        xit "creates a new Product" do
          expect {
            post products_url, params: { product: valid_attributes }
          }.to change(Product, :count).by(1)
        end

        xit "redirects to the created product" do
          post products_url, params: { product: valid_attributes }
          expect(response).to redirect_to(product_url(Product.last))
        end
      end

      context "with invalid parameters" do
        xit "does not create a new Product" do
          expect {
            post products_url, params: { product: invalid_attributes }
          }.to change(Product, :count).by(0)
        end

        xit "renders a successful response (i.e. to display the 'new' template)" do
          post products_url, params: { product: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        xit "updates the requested product" do
          product = Product.create! valid_attributes
          patch product_url(product), params: { product: new_attributes }
          product.reload
          skip("Add assertions for updated state")
        end

        xit "redirects to the product" do
          product = Product.create! valid_attributes
          patch product_url(product), params: { product: new_attributes }
          product.reload
          expect(response).to redirect_to(product_url(product))
        end
      end

      context "with invalid parameters" do
        xit "renders a successful response (i.e. to display the 'edit' template)" do
          product = Product.create! valid_attributes
          patch product_url(product), params: { product: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    describe "DELETE /destroy" do
      xit "destroys the requested product" do
        product = Product.create! valid_attributes
        expect {
          delete product_url(product)
        }.to change(Product, :count).by(-1)
      end

      xit "redirects to the products list" do
        product = Product.create! valid_attributes
        delete product_url(product)
        expect(response).to redirect_to(products_url)
      end
    end
  end
end
